### ISSUE TITLE
Sometime the items get mismatch 

### ISSUE THREAD

**Issue by MiTHUN24** [sacot41/SCViewPager#6]
Sometime the items get mismatch 

*they are overlap each other
*not having proper positioning
*this problem you can see in the sample you have given

**Comment by sacot41** [comment]
I don't see where the problem is with overlap, if you want the items to not overlapping, set your path to move as your wish. 

I'm not push new version of this code, if you want to use it, I recommend you to use this library : 
https://github.com/Nightonke/WoWoViewPager
It's the same code, with correction, and a lot of new animation.

**Comment by MiTHUN24** [comment]
Ok thanks for reply i seen that wowoviewpages lib and its greate i will use
that

Thanx,
:-)
